//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeviceMate.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accessory
    {
        public Accessory()
        {
            this.AccessoryHoldsHistories = new HashSet<AccessoryHoldsHistory>();
        }
    
        public int Id { get; set; }
        public string Number { get; set; }
        public int TypeId { get; set; }
        public string SerialNumber { get; set; }
        public int AccessoryDescriptionId { get; set; }
        public int AccessoryHoldId { get; set; }
        public Nullable<int> OsId { get; set; }
        public Nullable<int> ColorId { get; set; }
    
        public virtual AccessoryDescription AccessoryDescription { get; set; }
        public virtual AccessoryType AccessoryType { get; set; }
        public virtual Color Color { get; set; }
        public virtual Hold Hold { get; set; }
        public virtual OSs OSs { get; set; }
        public virtual ICollection<AccessoryHoldsHistory> AccessoryHoldsHistories { get; set; }
    }
}
