//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeviceMate.Models.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DeviceContext : DbContext
    {
        public DeviceContext()
            : base("name=DeviceContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Accessory> Accessories { get; set; }
        public DbSet<AccessoryDescription> AccessoryDescriptions { get; set; }
        public DbSet<AccessoryHoldsHistory> AccessoryHoldsHistories { get; set; }
        public DbSet<AccessoryType> AccessoryTypes { get; set; }
        public DbSet<Color> Colors { get; set; }
        public DbSet<DeviceHoldsHistory> DeviceHoldsHistories { get; set; }
        public DbSet<Device> Devices { get; set; }
        public DbSet<DeviceType> DeviceTypes { get; set; }
        public DbSet<GridColumn> GridColumns { get; set; }
        public DbSet<Grid> Grids { get; set; }
        public DbSet<Hold> Holds { get; set; }
        public DbSet<Manufacturer> Manufacturers { get; set; }
        public DbSet<Model> Models { get; set; }
        public DbSet<OSs> OSses { get; set; }
        public DbSet<ResolutionHeightOption> ResolutionHeightOptions { get; set; }
        public DbSet<Resolution> Resolutions { get; set; }
        public DbSet<ResolutionWidthOption> ResolutionWidthOptions { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<ScreenSize> ScreenSizes { get; set; }
        public DbSet<Status> Status { get; set; }
        public DbSet<Team> Teams { get; set; }
        public DbSet<Town> Towns { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<UsersGridColumn> UsersGridColumns { get; set; }
    }
}
