//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeviceMate.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceHoldsHistory
    {
        public int Id { get; set; }
        public System.DateTime HoldDate { get; set; }
        public int TeamId { get; set; }
        public string Email { get; set; }
        public bool IsBusy { get; set; }
        public int TownID { get; set; }
        public int DeviceId { get; set; }
    
        public virtual Device Device { get; set; }
        public virtual Team Team { get; set; }
        public virtual Town Town { get; set; }
    }
}
