//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeviceMate.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grid
    {
        public Grid()
        {
            this.GridColumns = new HashSet<GridColumn>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<GridColumn> GridColumns { get; set; }
    }
}
