//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeviceMate.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class GridColumn
    {
        public GridColumn()
        {
            this.UsersGridColumns = new HashSet<UsersGridColumn>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int GridId { get; set; }
    
        public virtual Grid Grid { get; set; }
        public virtual ICollection<UsersGridColumn> UsersGridColumns { get; set; }
    }
}
