//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeviceMate.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manufacturer
    {
        public Manufacturer()
        {
            this.Models = new HashSet<Model>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int OsId { get; set; }
    
        public virtual OSs OSs { get; set; }
        public virtual ICollection<Model> Models { get; set; }
    }
}
