//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeviceMate.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.UsersGridColumns = new HashSet<UsersGridColumn>();
        }
    
        public int Id { get; set; }
        public string Email { get; set; }
        public string Name { get; set; }
        public string Skype { get; set; }
        public string PictureUrl { get; set; }
        public string PictureResourceId { get; set; }
        public string Position { get; set; }
        public Nullable<int> TownId { get; set; }
        public bool IsAdmin { get; set; }
        public int StatusId { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public Nullable<int> TeamId { get; set; }
    
        public virtual Status Status { get; set; }
        public virtual Team Team { get; set; }
        public virtual Town Town { get; set; }
        public virtual ICollection<UsersGridColumn> UsersGridColumns { get; set; }
    }
}
